[workspace]
members = ["crates/*"]


# Patch for druid
[patch.crates-io]
direct2d = { git = 'https://github.com/edwin0cheng/direct2d-rs', branch="fix-close-gb" }
druid = { git = 'https://github.com/edwin0cheng/druid', branch="dev" }